//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juris.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juris.Resource.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete this resource because it&apos;s used.
        /// </summary>
        public static string CantDeleteResource {
            get {
                return ResourceManager.GetString("CantDeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send notification email to user.
        /// </summary>
        public static string CantSendEmail {
            get {
                return ResourceManager.GetString("CantSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upload file {0}.
        /// </summary>
        public static string CantUpload {
            get {
                return ResourceManager.GetString("CantUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with name={0} already exists.
        /// </summary>
        public static string CategoryNameExists {
            get {
                return ResourceManager.GetString("CategoryNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City with name={0} already exists.
        /// </summary>
        public static string CityNameExists {
            get {
                return ResourceManager.GetString("CityNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City with id={0} not found.
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education with id={0} not found.
        /// </summary>
        public static string EducationNotFound {
            get {
                return ResourceManager.GetString("EducationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience with id={id} not found.
        /// </summary>
        public static string ExperienceNotFound {
            get {
                return ResourceManager.GetString("ExperienceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size should be less than {0}MB.
        /// </summary>
        public static string FileSizeLess {
            get {
                return ResourceManager.GetString("FileSizeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of your profile on Juris has changed to &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string NewProfileStatusEmail {
            get {
                return ResourceManager.GetString("NewProfileStatusEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Status Updated.
        /// </summary>
        public static string NewProfileStatusSubject {
            get {
                return ResourceManager.GetString("NewProfileStatusSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0} {1}&lt;/strong&gt; wants to make an appointment with you. Check the details of the request on &lt;strong&gt;Juris&lt;/strong&gt;..
        /// </summary>
        public static string NewRequestEmail {
            get {
                return ResourceManager.GetString("NewRequestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment Request.
        /// </summary>
        public static string NewRequestSubject {
            get {
                return ResourceManager.GetString("NewRequestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Category with id={0} not found.
        /// </summary>
        public static string ProfileCategoryNotFound {
            get {
                return ResourceManager.GetString("ProfileCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile with id={0} not found.
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment request has been approved. You will be contacted shortly..
        /// </summary>
        public static string RequestApprovedEmail {
            get {
                return ResourceManager.GetString("RequestApprovedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Request Approved.
        /// </summary>
        public static string RequestApprovedSubject {
            get {
                return ResourceManager.GetString("RequestApprovedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment request has been declined. Don&apos;t worry we have other lawyer on our platform you can choose from..
        /// </summary>
        public static string RequestDeclinedEmail {
            get {
                return ResourceManager.GetString("RequestDeclinedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointmnet Request Declined.
        /// </summary>
        public static string RequestDeclinedSubject {
            get {
                return ResourceManager.GetString("RequestDeclinedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request with id={0} not found.
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review with id={0} not found.
        /// </summary>
        public static string ReviewNotFound {
            get {
                return ResourceManager.GetString("ReviewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized to change profile id={0}.
        /// </summary>
        public static string UnauthorizedProfileChange {
            get {
                return ResourceManager.GetString("UnauthorizedProfileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized to change request id={0}.
        /// </summary>
        public static string UnauthorizedRequestChange {
            get {
                return ResourceManager.GetString("UnauthorizedRequestChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file extension {0}.
        /// </summary>
        public static string UnsupportedFileExtension {
            get {
                return ResourceManager.GetString("UnsupportedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id={0} already has a profile.
        /// </summary>
        public static string UserHasProfile {
            get {
                return ResourceManager.GetString("UserHasProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id={0} not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
